spring.application.name=StudyProgress

spring.datasource.url=jdbc:postgresql://localhost:5432/studyprogress
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
